# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /builds/uwsbel/chrono/contrib/packaging-python/conda, last modified Sun Mar  1 10:18:26 2020
# ------------------------------------------------

package:
    name: pychrono
    version: 5.0.0
source:
    path: /builds/uwsbel/chrono
build:
    binary_relocation: true
    number: '9'
    rpaths:
        - lib/
    script_env:
        - CC
        - CXX
    string: py37_9
requirements:
    build:
        - bzip2 1.0.8 0
        - certifi 2019.9.11 py37_0
        - cmake 3.16.4 h28c56e5_0
        - expat 2.2.9 he1b5a44_2
        - intel-openmp 2020.0 intel_166
        - intelpython 2020.0 1
        - krb5 1.16.4 h2fd8d38_0
        - libcurl 7.68.0 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 11
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.34.0 h516909a_0
        - mkl 2020.0 intel_166
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d 0
        - pcre 8.44 he1b5a44_0
        - pip 19.1.1 py37_0
        - python 3.7.4 hf484d3e_3
        - rhash 1.3.6 h14c3975_1001
        - setuptools 41.0.1 py37_0
        - sqlite 3.29.0 0
        - swig 4.0.1 he1b5a44_0
        - tbb 2020.0 intel_166
        - tcl 8.6.4 24
        - tk 8.6.10 hed695b0_0
        - wheel 0.31.0 py37_3
        - xz 5.2.4 h14c3975_7
        - zlib 1.2.11 h14c3975_7
    run:
        - mkl
        - python >=3.7,<3.8.0a0
about:
    home: https://github.com/projectchrono/chrono
    license: BSD 3-Clause
    license_family: BSD
    summary: A physics engine for constrained multi-flexible-body dynamics
extra:
    copy_test_source_files: true
    final: true
